# Generated by Django 3.0.7 on 2020-06-24 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_url', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('board_description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(default='Anonymous', max_length=30)),
                ('post_subject', models.CharField(blank=True, max_length=50)),
                ('post_content', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='mainapp.Post')),
            ],
        ),
    ]
