# Generated by Django 3.0.7 on 2020-06-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_post_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='board',
            new_name='parent_board',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='parent',
            new_name='parent_post',
        ),
    ]
