# Generated by Django 3.0.7 on 2020-06-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200624_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenChan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='OpenChan', max_length=20)),
                ('site_desc', models.CharField(default='The Open Source Chan Software', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='post_counter',
            field=models.BigIntegerField(default=0),
        ),
    ]
