# Generated by Django 3.0.7 on 2020-06-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200624_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='local_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
