# Generated by Django 3.0.7 on 2020-06-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_post_local_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openchan',
            options={'verbose_name': 'Openchan Instance', 'verbose_name_plural': 'Openchan Instance'},
        ),
        migrations.AlterField(
            model_name='openchan',
            name='site_name',
            field=models.CharField(default='OpenChan', max_length=20, unique=True),
        ),
    ]
