# Generated by Django 3.0.7 on 2020-06-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200624_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mod_warning',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
