# Generated by Django 3.0.7 on 2020-06-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_post_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_subject', models.CharField(max_length=30)),
                ('news_content', models.TextField()),
                ('news_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='custom_cursor',
            field=models.ImageField(blank=True, null=True, upload_to='cursor/'),
        ),
        migrations.AddField(
            model_name='openchan',
            name='custom_cursor',
            field=models.ImageField(blank=True, null=True, upload_to='cursor/'),
        ),
    ]
